"""
Django settings for Our_Awesome_Project project.

Generated by 'django-admin startproject' using Django 3.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-h8pmru0$qa-4r032!cu&^jtn6w64emz8e(sh!6=me#k3w*s7-v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'driver_records',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Our_Awesome_Project.urls'


#Two lines added after importing os on top of this file
TEMPLATE_DIR_Our_Awesome_Project = os.path.join(BASE_DIR, "Our_Awesome_Project/templates")
TEMPLATE_DIR_highly_innovative_app_name = os.path.join(BASE_DIR, "driver_records/templates")



TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR_Our_Awesome_Project, TEMPLATE_DIR_highly_innovative_app_name],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Our_Awesome_Project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

"""DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}"""

#Commenting out the DATABASE dictionaries above since refactoring the app name to driver_records

DATABASE_ROUTERS = ['driver_records.router.DriverRecordsRouter']#Adding this above databases

#New DATABASE dictionaries below since refactoring the app name to driver_records
DATABASES = {
    'default': {},
    'driver_records_db': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'learning_mysql',
        'USER': 'app_user_2',
        'PASSWORD': 'fjewr98763rt7fgwoepifjo9382tgbiuw',
        'HOST': '35.158.101.51',
        'PORT': '3306',
     },
    some_stuff': {
        'ENGINE': 'djongo',
        'NAME': 'learning_nosql',
        'ENFORCE_SCHEMA': False,
        'CLIENT': {
            'host': 'mongodb://app_admin_2:wfjh9ew76y9833yhfr98o3yfr987iyf87tt382tfg8i@35.158.101.51/learning_nosql?retryWrites=true&w=majority'
        }
    },
    'employee_records_db': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'learning_postgre',
        'USER': 'app_admin',
        'PASSWORD': 'wfjh9ew76y9833yhfr98o3yfr987iyf87tt382tfg8i',
        'HOST': '35.158.101.51',
        'PORT': '5432',
    }
}



# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
